### ISSUE TITLE
owncloud_zimlet_app_title and accented letters

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/owncloud-zimlet#191] opened 2018-12-18 11:45 UTC
owncloud_zimlet_app_title with accented letters.

Please advise how to modify: owncloud_zimlet_app_title in:
```
/opt/zimbra/lib/ext/ownCloud/config.properties
```
so that accented letters are displayed properly.

In the current test if you use:
```
Núvol
```
string then the tab is displayed similar to:
```
N?vol
```
.

Thank you very much for any idea you can give us.

**Comment by barrydegraaff** [comment] 2018-12-18 12:08
Try encoding it with unicode conversion see: http://itpro.cz/juniconv/

**Comment by adriangibanelbtactic** [comment] 2019-01-04 17:13
So far I have tried:
```
\u00FA
```
.

1. When used in:
```
/opt/zimbra/lib/ext/ownCloud/config.properties
```
file it gets converted by prop2xml.jar program into ? symbol.

2. When used in:
```
/opt/zimbra/zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/config_template.xml
```
after which you need to run:
```
$ zmzimletctl configure /opt/zimbra/zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/config_template.xml
$ zmmailboxdctl restart
```
the
```
\u00FA
```
string is used literally.

**Comment by adriangibanelbtactic** [comment] 2019-01-04 17:30
When used in:
/opt/zimbra/zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/config_template.xml
after which you need to run:

$ zmzimletctl configure /opt/zimbra/zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/config_template.xml
$ zmmailboxdctl restart
the

```
&#x00FA;
```
string seems to do the trick.

Next test will be to edit config.properties file and see what prop2xml.jar does with it.

https://support.crossref.org/hc/en-us/articles/215652783-Special-characters-in-your-XML
https://graphemica.com/%C3%BA

**Comment by barrydegraaff** [comment] 2019-01-08 12:53
I can confirm prop2xml is broken

**Comment by barrydegraaff** [comment] 2019-01-08 12:54
The cause is that `N\u00FAvol` is put as `Núvol` in the XML, but it should remain encoded as `N\u00FAvol`

**Comment by barrydegraaff** [comment] 2019-01-08 13:10
New version of prop2xml is uploaded, it should take care of this issue.

**Comment by barrydegraaff** [comment] 2019-01-08 13:13
propmigr.jar is not affected by this

**Comment by adriangibanelbtactic** [comment] 2019-01-08 15:05
> The cause is that N\u00FAvol is put as Núvol in the XML, but it should remain encoded as N\u00FAvol
According to my former tests using N\u00FAvol in the XML is not ok because it gets shown literally. Have you tested it?

Using N&#x00FA;vol should be right thing to do.

**Comment by barrydegraaff** [comment] 2019-01-08 17:43
@adriangibanelbtactic thanks for testing, I committed new version, please confirm this fixes the issue.

**Closed** 2019-01-08 17:42 UTC
